### ISSUE TITLE
Add quiet option

### ISSUE THREAD

**Issue by kamilbrk** [rejas/gulp-modernizr#25]
Is there a way to pass `quiet` option to customizr from gulpfile?

https://github.com/doctyper/customizr/blob/develop/src/crawler.js#L8

**Comment by ScottSmith95** [comment]
+1 for this

**Comment by shakyShane** [comment]
+1

**Comment by davidknezic** [comment]
+1

**Comment by felics** [comment]
+1

**Comment by rejas** [comment]
Quiet option has to be fixed first in customizr, PR for that is pushed: https://github.com/Modernizr/customizr/pull/54

**Comment by rejas** [comment]
Fixed in v3.0.0
