### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by taupecat** [rejas/gulp-modernizr#30]
The npm `modernizr` package can read a JSON config file (as in this article: http://webdesign.tutsplus.com/tutorials/a-quick-look-at-modernizr-30--cms-24932)

Any plans to include the ability to do that in the gulp-modernizr plugin?

**Comment by hiromipaw** [comment]
This would actually be very helpful.

**Comment by andyinabox** [comment]
+1, although maybe this is an issue for the [customizr](https://github.com/doctyper/customizr) module?

**Comment by JiDai** [comment]
You can pass a 'settings' object so you can require a JSON file :

```
gulp.task('modernizr', function() {
  gulp.src('./js/*.js')
    .pipe(modernizr(require('./modernizr-config.json')))
    .pipe(gulp.dest("build/"))
});
```

**Comment by rejas** [comment]
@JiDai is correct, you can use gulp-modernizr like this:

modernizr.config.js:
```
{
        'options': ['setClasses'],
        'tests': ['webworkers']
}
```

gulpfile.babel.js:
```
import config from './modernizr.config.js';

gulp.task('prepare:modernizr', () => {
    return gulp.src('./js/*.js')
        .pipe(modernizr('modernizr.min.js', config))
        .pipe(gulp.dest(`${dirs.src}/js/vendor`));
});
```
