### ISSUE TITLE
npm install fails in postinstall.js

### ISSUE THREAD

**Issue by intermension** [rejas/gulp-modernizr#32]
I'm unable to install this package as it fails as below:

12244 info install customizr@1.0.0-alpha
12245 info postinstall customizr@1.0.0-alpha
12246 verbose unsafe-perm in lifecycle true
12247 info customizr@1.0.0-alpha Failed to exec postinstall script
12248 verbose unlock done using C:\Users\Admin\AppData\Roaming\npm-cache_locks\customizr-87ff1bcc5d05333b.lock for D:\Devzone\InstallersCache\InstallersCache\node_modules\gulp-modernizr\node_modules\customizr
12249 verbose about to build D:\Devzone\InstallersCache\InstallersCache\node_modules\gulp-modernizr
12250 verbose unlock done using C:\Users\Admin\AppData\Roaming\npm-cache_locks\gulp-modernizr-32c9da1f744e76b7.lock for D:\Devzone\InstallersCache\InstallersCache\node_modules\gulp-modernizr
12251 verbose stack Error: customizr@1.0.0-alpha postinstall: `node scripts/postinstall.js`
12251 verbose stack Exit status 1
12251 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
12251 verbose stack     at emitTwo (events.js:87:13)
12251 verbose stack     at EventEmitter.emit (events.js:172:7)
12251 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
12251 verbose stack     at emitTwo (events.js:87:13)
12251 verbose stack     at ChildProcess.emit (events.js:172:7)
12251 verbose stack     at maybeClose (internal/child_process.js:818:16)
12251 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
12252 verbose pkgid customizr@1.0.0-alpha
12253 verbose cwd D:\Devzone\InstallersCache\InstallersCache
12254 error Windows_NT 6.2.9200
12255 error argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "gulp-modernizr" "--save-dev"
12256 error node v4.2.1
12257 error npm  v2.14.7
12258 error code ELIFECYCLE
12259 error customizr@1.0.0-alpha postinstall: `node scripts/postinstall.js`
12259 error Exit status 1
12260 error Failed at the customizr@1.0.0-alpha postinstall script 'node scripts/postinstall.js'.
12260 error This is most likely a problem with the customizr package,
12260 error not with npm itself.
12260 error Tell the author that this fails on your system:
12260 error     node scripts/postinstall.js
12260 error You can get their info via:
12260 error     npm owner ls customizr
12260 error There is likely additional logging output above.
12261 verbose exit [ 1, true ]
12262 verbose unbuild node_modules\gulp-modernizr\node_modules\customizr
12263 info preuninstall customizr@1.0.0-alpha
12264 info uninstall customizr@1.0.0-alpha
12265 verbose unbuild rmStuff customizr@1.0.0-alpha from D:\Devzone\InstallersCache\InstallersCache\node_modules

**Comment by neilcarpenter** [comment]
+1

**Comment by jim-hm** [comment]
I have this issue too.

**Comment by rejas** [comment]
Hi @intermension @neilcarpenter @jim-hm is this still an issue for you with the newest version (2.0.0) or did you already move on?

**Comment by rejas** [comment]
Closed due to inactivity
