### ISSUE TITLE
Use Modernizr without gulp.src

### ISSUE THREAD

**Issue by JiDai** [rejas/gulp-modernizr#35]
Hi,

Why must I add src of some JS files before use modernizr ? Can I use modernizr directly ?

```
gulp.task('modernizr', function() {
  gulp.src('./js/*.js')
    .pipe(modernizr())
    .pipe(gulp.dest("build/"))
});
```

Thanks for help

**Comment by Hiswe** [comment]
I think that this plugin is meant to make a custom build of modernizr by analyzing your CSS/JS files.
So you won't need to take care of which tests you are using when you'r doing the build.

And also gulp is designed to act on files :) So if you don't need to parse those files, you shouldn't need gulp for this specific task :)

**Comment by asppsa** [comment]
Hey, I've just hacked a basic modernizr gulp stream together that doesn't use customizr (so lets you choose your features by hand).  Code is as follows:

~~~
var gulp = require('gulp'),
    modernizr = require('modernizr'),
    File = require('vinyl'),
    stream = require('stream');

// This function produces a stream.
// - First arg is the desired file name (e.g. modernizr.js),
// - second arg is a set of options to pass to the modernizr function.
function modernizrStream(name, options) {
  var wasWritten = false;

  return new stream.Readable({
    objectMode: true,
    read: function (size) {
      var self = this;
      modernizr.build(options, function (result) {
        if (!wasWritten) {
          self.push(new File({
            path: process.cwd() + "/" + name,
            contents: new Buffer(result)
          }));

          wasWritten = true;
          self.push(null);
        }
      });
    }
  })
}

// Here's an example ...
gulp.task('modernizr', function () {
  modernizrStream('modernizr.js', {
    "feature-detects": [
      "es5/array",
      "es5/date",
      "es5/function",
      "es5/object",
      "es5/specification",
      "es5/strictmode",
      "es5/string",
      "es5/syntax",
      "es5/undefined",
      "eventlistener",
      "history",
      "network/fetch"
    ]
  }).pipe(gulp.dest('public/'));
});
~~~

**Comment by rejas** [comment]
@Hiswe is correct, this plugin takes src-files and scans them for Modernizr references so it can generate a custom build. If it is still an issue for you @JiDai please say so.

**Comment by Bigdragon13th** [comment]
That `gulp.src` thing curious me for a long time. Thanks for clarifying! @Hiswe @rejas . Maybe those explanation on homepage would help some more people.

One more question, so is this mean I don't need to include any tests in setting, gulp-modernizr will scan my files and grap whatever tests I wrote in their?

**Comment by rejas** [comment]
Correct @Bigdragon13th So for example if in your src files there is a line like 
`        if (!Modernizr.objectfit) {
            doSomethingLikeCallAPolyfill();
        }
`
this plugin will add the `objectfit `tests to the generated modernizr build (which can best saved somewehre via `gulp.dest`

**Comment by rejas** [comment]
Added this explanation to the README and closing the ticket for now
