### ISSUE TITLE
"crawl: false" being ignored

### ISSUE THREAD

**Issue by stiefdirckx** [rejas/gulp-modernizr#36]
I've set in my task configuration not to crawl my source files but the output says it's still doing so.

``` javascript
gulp.task("modernizr", function () {
    return gulp.src(paths.scripts + "*.js")
        .pipe(modernizr(config.modernizr, { "crawl": false, "options": ["mq", "setClasses"], "tests": ["pointerevents", "touchevents"] }))
        .pipe(gulp.dest("."));
});
```

The output says: `Looking for Modernizr references` and the resulting file also contains more tests than configured.

**Comment by mcclaskiem** [comment]
Ive got a similar issue here

**Comment by rejas** [comment]
Yeah, the plugin doesnt respect this option:

inde.xjs, line 28-29
```
// Set crawl to false, Gulp is providing files & data
opt.crawl = false;
```

Maybe @doctyper can find the time and explain the reasoning behind it?

**Comment by rejas** [comment]
Hi @stiefdirckx  @mcclaskiem sorry for not replying yet. Maybe you already moved on but could you provide your options/config for the gulp task? What gulp.src especially do you pipe to the plugin?

**Comment by stiefdirckx** [comment]
@rejas I'm no longer working on the project where I found this issue and I don't have access to the code anymore.  Sorry.

**Comment by rejas** [comment]
no worries @stiefdirckx but I will be closing this issue then.
