### ISSUE TITLE
touchevents + ES6

### ISSUE THREAD

**Issue by valeriosillari** [rejas/gulp-modernizr#43]
Probably I am doing something wrong, but I am new to ES6 ....

I want to use the `touchevents` options in a project where i am generating a custom modernizr js file trough this gulp plugin.

here my code:

**---------------------------------**
**GULP TASK:**
gulp.task('modernizr', () => {
    // check the js files
    return gulp.src([
        `folderSrc/**/*.js`,
    ])
        // custom options
        .pipe(modernizr({
            'options' : [
                'setClasses',
                'addTest',
                'testProp',
                'fnBind',
            ],
            // Define any tests you want to explicitly include : HERE my problem?
            'feature-detects': [
                'touchevents',
            ],
        }))
        // generate a custom JS file
        .pipe(gulp.dest(
            `fileDist.js`,
        ));
});

**---------------------------------**
**GULP IMPLEMENTATION:**
// call the modernizr JS file as a module
import Modernizr from 'modernizr';

// try to check if  we have the touchevenets. HERE value is UNDEFINED
console.info(Modernizr.touchevents);

At this step I have the 'touchevents' classes appended to the html tag, and modernizr works.
But the console log in the js for the touch events return undefined.

probably i made a mistake in the task configuration. but i have no idea.. 

Help please :)

**Comment by remisture** [comment]
This works for me.

```
gulp.task('modernizr', function() {
    gulp.src(['/**/*.js'])
    .pipe(modernizr({
        options : [
            'setClasses',
            'testProp',
            'testprop',
            'fnBind'
        ],
        tests : ['touchevents']
    }))
    .pipe(gulp.dest('fileDist.js'))
});
```

**Comment by rejas** [comment]
@valeriosillari is this still an issue for you or can we close it?

**Comment by valeriosillari** [comment]
I closed it :)
