### ISSUE TITLE
Supported version

### ISSUE THREAD

**Issue by daronjones** [rejas/gulp-modernizr#51]
It says in the documentation that version 3 is supported. Just wondering if you support patch versions under 3, specifically 3.5 which adds support for grid detection.

If not is there any chance that this would be something that would be on the cards in the near future?

**Comment by rejas** [comment]
hi @daronjones not sure what you mean: do you really want to have a build based on an old version (2.X9 of modernizr? because this plugin here will always build with the latest Modernizr version (which is currently 3.6). I have no plans whatsoever on supporting building old modernirz for obvious security and matainance reasons.

**Comment by markkes** [comment]
@rejas It might be that @daronjones has the same issue as i have.

I cant seem to get the grid support to work using the "tests" option. It is working via the feature detection scanning the JS files. But when i add it to the gulp function via the "tests" option it ignores is. I just want to add it as an extra test running and adding it to the modenizr build. Can you reproduce this issue?

**Comment by rejas** [comment]
I can but a) it seems to only concern tests that have an array of properties (like cssgrid, but not something like svg) and b) is rooted in customizr (which I thought was fixed already via https://github.com/Modernizr/customizr/pull/44)

**Comment by rejas** [comment]
Further looking into it, it does work, the config has to be
```
    {
        "options": ["setClasses"],
        "tests": [
            [
                "cssgrid",
                "cssgridlegacy"
            ]
        ],
    }
```

though. Can you confirm @markkes  ?

**Comment by markkes** [comment]
@rejas Works, thanks for the quick reply and solution!

**Comment by rejas** [comment]
@markkes good to hear that. updated the readme with an example on how to include tests like that for grids.
